-- Active: 1768245236744@@127.0.0.1@5432@spender
DROP DATABASE IF EXISTS spender;

CREATE DATABASE spender;

\c spender;


-- Drop child tables first

DROP TABLE IF EXISTS user_ips;
DROP TABLE IF EXISTS login_logs;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS carte;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

-- users(#userId , firstname, lastname, email, password, role, join_date)
-- categories(#id, name, type, user_id, monthly_limit)
-- transactions(#id, title, description, type, amount, date, status, user_id, category_id, card_id, transfer_id)
-- carte(#id, name, user_id, balance, limit, expiry_date, card_number)
-- transfers(#id, sender_id, receiver_id, amount, date)

CREATE TABLE users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'user',
    join_date DATE DEFAULT CURRENT_DATE
);

-- Default admin/user for testing
insert into users(firstname, lastname , email , password, role)
values('Admin', 'User', 'admin@spender.com', '$2y$10$XKtB6k/WWczwP3.v6LLnmu4d.apLewRKXWtKYzoJMkBOiYdKbLrSC', 'admin');

CREATE TABLE categories (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(20) DEFAULT 'expense', -- expense or income
    user_id INT,
    monthly_limit DECIMAL(10, 2) DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE carte (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    user_id INT NOT NULL,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0,
    credit_limit DECIMAL(10, 2) DEFAULT 0,
    expiry_date DATE,
    card_number VARCHAR(20) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE transfers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id INT, -- user_id or card_id context
    receiver_id INT,
    amount DECIMAL(10, 2) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    -- Logic for transfers can be complex (User to User, Card to Card?), keeping simple for now
);

CREATE TABLE transactions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    description TEXT,
    user_id INT NOT NULL,
    category_id INT,
    type VARCHAR(20) NOT NULL, -- expense, income, transfer
    amount DECIMAL(10, 2) NOT NULL,
    transaction_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'completed',
    card_id INT,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    FOREIGN KEY (card_id) REFERENCES carte (id) ON DELETE SET NULL
);

CREATE TABLE user_ips (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE login_logs (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE notifications (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    message TEXT NOT NULL,
    seen INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

