DROP DATABASE IF EXISTS spender;

CREATE DATABASE spender;

\c spender;


-- Drop child tables first
DROP TABLE IF EXISTS otp_codes;

DROP TABLE IF EXISTS user_ips;

DROP TABLE IF EXISTS login_logs;

DROP TABLE IF EXISTS notifications;

DROP TABLE IF EXISTS transactions;

DROP TABLE IF EXISTS income;

DROP TABLE IF EXISTS expense;

DROP TABLE IF EXISTS carte;

DROP TABLE IF EXISTS transfert;
-- Drop parent tables last
DROP TABLE IF EXISTS categories;

DROP TABLE IF EXISTS users;

-- users(#userId , firstname, lastname, email, password, join_date)
-- expense(#expenseId, expenseTitle, description, price, categorie , duedate, state , user_id#)
-- income(#incomeId, incomeTitle, description , price, categorie, getIncomeDate, user_id#)
-- categories(#categoryId, name)
--  transactions(#transactionId, title, description, type, amount , transaction_date, state, user_id#, category_id#)
-- user_ips(#id,id_adress, created_at, user_id#)
-- otp_codes(#id, otp_code, expires_at, used, created_at, user_id#)
-- login_logs(#id, ip_adress, status, created_at, user_id#)
-- carte(#idCard, nom, user_id, currentSold,limite, statue, expireDate, num, user_id# )
-- notifications(#id, message, seen , created_at, user_id#)

CREATE TABLE users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    join_date DATE DEFAULT CURRENT_DATE
);

insert into users(firstname, lastname , email , password)
values('test','test','test@test.test','$2y$10$XKtB6k/WWczwP3.v6LLnmu4d.apLewRKXWtKYzoJMkBOiYdKbLrSC');


CREATE TABLE expense (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    expenseTitle VARCHAR(50) NOT NULL,
    description TEXT,
    user_id INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    categorie TEXT,
    dueDate DATE,
    state VARCHAR(20) DEFAULT 'not paid',
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE income (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    incomeTitle VARCHAR(50) NOT NULL,
    description TEXT,
    user_id INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    categorie TEXT,
    getIncomeDate DATE,
    CONSTRAINT fk_income_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE categories (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE transactions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    description TEXT,
    user_id INT NOT NULL,
    category_id INT,
    type text NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    transaction_date DATE NOT NULL,
    state VARCHAR(20) DEFAULT 'not paid',
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE user_ips (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE otp_codes (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    otp_code VARCHAR(6) NOT NULL,
    expires_at DATE NOT NULL,
    used INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE login_logs (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE notifications (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    message TEXT NOT NULL,
    seen INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE carte (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom TEXT NOT NULL,
    user_id INT NOT NULL,
    currentSold INT NOT NULL DEFAULT 0,
    limite INT NOT NULL DEFAULT 0,
    expireDate DATE,
    num INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE transfert (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idSender INT NOT NULL,
    idReceiver INT NOT NULL,
    amount INT NOT NULL,
    daySent DATE DEFAULT CURRENT_TIMESTAMP
);
-- modifying the categories table
ALTER TABLE categories
ADD monthly_limit DECIMAL(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE categories
ADD COLUMN user_id INT NOT NULL,
ADD CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE TABLE expense_events (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    original_expense_id INT NOT NULL,
    last_generated INT NOT NULL,
    day_of_month DATE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE expense
ADD COLUMN card_id INT,
ADD CONSTRAINT fk_expense_card FOREIGN KEY (card_id) REFERENCES carte (id) ON DELETE SET NULL;



select * from users;
